export const NEW_STAMP_INV = '[STAMP_INV APP] NEW STAMP DUTY';

export const SAVE_STAMP_INV_INIT_REQUEST = '[STAMP_INV APP] SAVE STAMP DUTY INIT REQUEST';
export const SAVE_STAMP_INV_SUCCESS = '[STAMP_INV APP] SAVE STAMP DUTY SUCCESS';
export const SAVE_STAMP_INV_FAILURE = '[STAMP_INV APP] SAVE STAMP DUTY FAILURE';

export const OPEN_ADD_STAMP_INV_DIALOG = '[STAMP_INV APP] OPEN ADD STAMP DUTY DIALOG';
export const CLOSE_ADD_STAMP_INV_DIALOG = '[STAMP_INV APP] CLOSE ADD STAMP DUTY DIALOG';
export const REMOVE_STAMP_INV = '[STAMP_INV APP] REMOVE STAMP';

export const ADD_STAMP_INV = '[STAMP_INV APP] ADD STAMP';

export const GET_STAMP_INV_INIT_REQUEST = '[STAMP_INV APP] GET STAMP DUTY INIT REQUEST';
export const GET_STAMP_INV_SUCCESS = '[STAMP_INV APP] GET STAMP DUTY SUCCESS';
export const GET_STAMP_INV_FAILURE = '[STAMP_INV APP] GET STAMP DUTY FAILURE';
