export const SET_STAMP_INV_SEARCH_CRITERIA = '[STAMP_INV APP] SET STAMP DUTY SEARCH CRITERIA';
export const GET_STAMP_INV_REQUEST_INIT = '[STAMP_INV APP] GET STAMP INV REQUEST INIT';
export const GET_STAMP_INV_SUCCESS = '[STAMP_INV APP] GET STAMP INV SUCCESS';
export const GET_STAMP_INV_FAILURE = '[STAMP_INV APP] GET STAMP INV FAILURE';
export const OPEN_CHANGE_STATE_DIALOG = '[STAMP_INV APP] OPEN CHANGE STATE DIALOG';
export const CLOSE_CHANGE_STATE_DIALOG = '[STAMP_INV APP] CLOSE CHANGE STATE DIALOG';
export const CHANGE_STAMP_INV_STATUS_INIT = '[STAMP_INV APP] CHANGE STAMP INV STATUS INIT';
export const CHANGE_STAMP_INV_STATUS_SUCCESS = '[STAMP_INV APP] CHANGE STAMP INV STATUS SUCCESS';
export const CHANGE_STAMP_INV_STATUS_FAILURE = '[STAMP_INV APP] CHANGE STAMP INV STATUS FAILURE';
export const GET_STATUS_FLOW = '[STAMP_INV APP] GET STATUS FLOW';

export const OPEN_RETURN_STAMP_OPTIONS_DIALOG = '[STAMP_INV APP] OPEN RETURN STAMP OPTIONS DIALOG';
export const CLOSE_RETURN_STAMP_OPTIONS_DIALOG = '[STAMP_INV APP] CLOSE RETURN STAMP OPTIONS DIALOG';

export const SAVE_STAMP_INV_RETURN_INIT_REQUEST = '[STAMP_INV APP] SAVE STAMP INV RETURN INIT REQUEST';
export const SAVE_STAMP_INV_RETURN_SUCCESS = '[STAMP_INV APP] SAVE STAMP INV RETURN SUCCESS';
export const SAVE_STAMP_INV_RETURN_FAILURE = '[STAMP_INV APP] SAVE STAMP INV RETURN FAILURE';