export const GET_PAYMENT_RECEIPTS_INIT_REQUEST = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPTS INIT REQUEST';
export const GET_PAYMENT_RECEIPTS_SUCCESS = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPTS SUCCESS';
export const GET_PAYMENT_RECEIPTS_FAILURE = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPTS FAILURE';

export const SET_PAYMENT_RECEIPT_SEARCH_TEXT = '[PAYMENT RECEIPT APP] SET PAYMENT RECEIPT SEARCH TEXT';

export const OPEN_CHANGE_STATE_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] OPEN CHANGE STATE PAYMENT RECEIPT DIALOG';
export const CLOSE_CHANGE_STATE_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] CLOSE CHANGE STATE PAYMENT RECEIPT DIALOG';

export const CHANGE_PAYMENT_RECEIPT_STATUS_INIT = '[PAYMENT RECEIPT APP] CHANGE PAYMENT RECEIPT STATUS INIT';
export const CHANGE_PAYMENT_RECEIPT_STATUS_SUCCESS = '[PAYMENT RECEIPT APP] CHANGE PAYMENT RECEIPT STATUS SUCCESS';
export const CHANGE_PAYMENT_RECEIPT_STATUS_FAILURE = '[PAYMENT RECEIPT APP] CHANGE PAYMENT RECEIPT STATUS FAILURE';
