export const GET_PAYMENT_RECEIPT_INIT_REQUEST = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPT INIT REQUEST';
export const GET_PAYMENT_RECEIPT_SUCCESS = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPT SUCCESS';
export const GET_PAYMENT_RECEIPT_FAILURE = '[PAYMENT RECEIPT APP] GET PAYMENT RECEIPT FAILURE';

export const NEW_PAYMENT_RECEIPT = '[PAYMENT RECEIPT APP] NEW PAYMENT RECEIPT';

export const SAVE_PAYMENT_RECEIPT_INIT_REQUEST = '[PAYMENT RECEIPT APP] SAVE PAYMENT RECEIPT INIT_REQUEST';
export const SAVE_PAYMENT_RECEIPT_SUCCESS = '[PAYMENT RECEIPT APP] SAVE PAYMENT RECEIPT SUCCESS';
export const SAVE_PAYMENT_RECEIPT_FAILURE = '[PAYMENT RECEIPT APP] SAVE PAYMENT RECEIPT FAILURE';

export const OPEN_TRANS_DETAILS_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] OPEN TRANSACTION DETAILS PAYMENT RECEIPT DIALOG';
export const CLOSE_TRANS_DETAILS_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] CLOSE TRANSACTION DETAILS PAYMENT RECEIPT DIALOG';
export const EDIT_TRANS_DETAILS_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] EDIT TRANSACTION DETAILS PAYMENT RECEIPT DIALOG';

export const DELETE_TRANS_DETAIL_PAYMENT_RECEIPT = '[PAYMENT RECEIPT APP] DELETE TRANSACTION DETAIL PAYMENT RECEIPT';
export const CREATE_TRANS_DETAIL_PAYMENT_RECEIPT = '[PAYMENT RECEIPT APP] CREATE TRANSACTION DETAIL PAYMENT RECEIPT';

export const GET_PAYMENT_BALANCE_INIT_REQUEST = '[PAYMENT RECEIPT APP] GET PAYMENT BALANCE INIT_REQUEST';
export const GET_PAYMENT_BALANCE_SUCCESS = '[PAYMENT RECEIPT APP] GET PAYMENT BALANCE SUCCESS';
export const GET_PAYMENT_BALANCE_FAILURE = '[PAYMENT RECEIPT APP] GET PAYMENT BALANCE FAILURE';

export const OPEN_BALANCE_DETAILS_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] OPEN BALANCE DETAILS PAYMENT RECEIPT DIALOG';
export const CLOSE_BALANCE_DETAILS_PAYMENT_RECEIPT_DIALOG = '[PAYMENT RECEIPT APP] CLOSE BALANCE DETAILS PAYMENT RECEIPT DIALOG';
export const CREATE_BALANCE_DETAIL_PAYMENT_RECEIPT = '[PAYMENT RECEIPT APP] CREATE BALANCE DETAIL PAYMENT RECEIPT';
export const DELETE_BALANCE_DETAILS_PAYMENT_RECEIPT = '[PAYMENT RECEIPT APP] DELETE BALANCE DETAILS PAYMENT RECEIPT';
