export const GET_CASE_ACTIVITIES_INIT_REQUEST = '[CASE-ACTIVITIES APP] GET CASE ACTIVITIES INIT REQUEST';
export const GET_CASE_ACTIVITIES_SUCCESS = '[CASE-ACTIVITIES APP] GET CASE ACTIVITIES SUCCESS';
export const GET_CASE_ACTIVITIES_FAILURE = '[CASE-ACTIVITIES APP] GET CASE ACTIVITIES FAILURE';

export const SET_CASE_ACTIVITIES_SEARCH_TEXT = '[CASE-ACTIVITIES APP] SET CASE ACTIVITIES SEARCH TEXT';

export const CREATE_CASE_ACTIVITIES_INIT_REQUEST = '[CASE-ACTIVITIES APP] CREATE CASE ACTIVITIES INIT REQUEST';
export const CREATE_CASE_ACTIVITIES_SUCCESS = '[CASE-ACTIVITIES APP] CREATE CASE ACTIVITIES SUCCESS';
export const CREATE_CASE_ACTIVITIES_FAILURE = '[CASE-ACTIVITIES APP] CREATE CASE ACTIVITIES FAILURE';

export const OPEN_NEW_CASE_ACTIVITY_DIALOG = '[CASE-ACTIVITIES APP] OPEN NEW CASE ACTIVITY DIALOG';
export const CLOSE_NEW_CASE_ACTIVITY_DIALOG = '[CASE-ACTIVITIES APP] CLOSE NEW CASE ACTIVITY DIALOG';
export const CLOSE_EDIT_CASE_ACTIVITY_DIALOG = '[CASE-ACTIVITIES APP] CLOSE EDIT CASE ACTIVITY DIALOG';

export const GET_CASE_ACTIVITY_INIT_REQUEST = '[CASE-ACTIVITIES APP] GET CASE ACTIVITY INIT REQUEST';
export const OPEN_EDIT_CASE_ACTIVITY_DIALOG = '[CASE-ACTIVITIES APP] OPEN EDIT CASE ACTIVITY DIALOG';
export const GET_CASE_ACTIVITY_FAILURE = '[CASE-ACTIVITIES APP] GET CASE ACTIVITY FAILURE';

export const REMOVE_CASE_ACTIVITY_INIT_REQUEST = '[CASE-ACTIVITIES APP] REMOVE CASE ACTIVITY INIT_REQUEST';
export const REMOVE_CASE_ACTIVITY_SUCCESS = '[CASE-ACTIVITIES APP] REMOVE CASE ACTIVITY SUCCESS';
export const REMOVE_CASE_ACTIVITY_FAILURE = '[CASE-ACTIVITIES APP] REMOVE CASE ACTIVITY FAILURE';

export const OPEN_CHANGE_RECORD_DIALOG = '[CASE-ACTIVITIES APP] OPEN CASE ACTIVITY DIALOG';
export const CLOSE_CHANGE_RECORD_DIALOG = '[CASE-ACTIVITIES APP] CLOSE CASE ACTIVITY DIALOG';

export const UPDATE_RECORD_CASE_ACTIVITIES_INIT_REQUEST = '[CASE-ACTIVITIES APP] UPDATE RECORD CASE ACTIVITIES INIT REQUEST';
export const UPDATE_RECORD_CASE_ACTIVITIES_SUCCESS = '[CASE-ACTIVITIES APP] UPDATE RECORD CASE ACTIVITIES SUCCESS';
export const UPDATE_RECORD_CASE_ACTIVITIES_FAILURE = '[CASE-ACTIVITIES APP] UPDATE RECORD CASE ACTIVITIES FAILURE';
