export const SET_STAMP_MOV_SEARCH_CRITERIA = '[STAMP MOV APP] SET STAMP MOV SEARCH CRITERIA';
export const GET_STAMP_MOV_INIT_REQUEST = '[STAMP MOV APP] GET STAMP MOV INIT REQUEST';
export const GET_STAMP_MOV_SUCCESS = '[STAMP MOV APP] GET STAMP MOV SUCCESS';
export const GET_STAMP_MOV_FAILURE = '[STAMP MOV APP] GET STAMP MOV FAILURE';