const deparments = [
  { id: 1, label: 'Guatemala, Guatemala' },
  { id: 2, label: 'Santa Catarina Pinula, Guatemala' },
  { id: 3, label: 'San José Pinula, Guatemala' },
  { id: 4, label: 'San José del Golfo, Guatemala' },
  { id: 5, label: 'Palencia, Guatemala' },
  { id: 6, label: 'Chinautla, Guatemala' },
  { id: 7, label: 'San Pedro Ayampuc, Guatemala' },
  { id: 8, label: 'Mixco, Guatemala' },
  { id: 9, label: 'San Pedro Sacatepéquez, Guatemala' },
  { id: 10, label: 'San Juan Sacatepéquez, Guatemala' },
  { id: 11, label: 'San Raymundo, Guatemala' },
  { id: 12, label: 'Chuarrancho, Guatemala' },
  { id: 13, label: 'Fraijanes, Guatemala' },
  { id: 14, label: 'Amatitlán, Guatemala' },
  { id: 15, label: 'Villa Nueva, Guatemala' },
  { id: 16, label: 'Villa Canales, Guatemala' },
  { id: 17, label: 'San Miguel Petapa, Guatemala' },
  { id: 18, label: 'Cobán, Alta Verapaz' },
  { id: 19, label: 'San Pedro Carchá, Alta Verapaz' },
  { id: 20, label: 'San Juan Chamelco, Alta Verapaz' },
  { id: 21, label: 'San Cristóbal Verapaz, Alta Verapaz' },
  { id: 22, label: 'Tactic, Alta Verapaz' },
  { id: 23, label: 'Tucurú, Alta Verapaz' },
  { id: 24, label: 'Tamahú, Alta Verapaz' },
  { id: 25, label: 'Panzós, Alta Verapaz' },
  { id: 26, label: 'Senahú, Alta Verapaz' },
  { id: 27, label: 'Cahabón, Alta Verapaz' },
  { id: 28, label: 'Lanquín, Alta Verapaz' },
  { id: 29, label: 'Chahal, Alta Verapaz' },
  { id: 30, label: 'Fray Bartolomé de las Casas, Alta Verapaz' },
  { id: 31, label: 'Chisec, Alta Verapaz' },
  { id: 32, label: 'Santa Cruz Verapaz, Alta Verapaz' },
  { id: 33, label: 'Santa Catalina La Tinta, Alta Verapaz' },
  { id: 34, label: 'Raxruhá, Alta Verapaz' },
  { id: 35, label: 'Cubulco, Baja Verapaz' },
  { id: 36, label: 'Santa Cruz el Chol, Baja Verapaz' },
  { id: 37, label: 'Granados, Baja Verapaz' },
  { id: 38, label: 'Purulhá, Baja Verapaz' },
  { id: 39, label: 'Rabinal, Baja Verapaz' },
  { id: 40, label: 'Salamá, Baja Verapaz' },
  { id: 41, label: 'San Miguel Chicaj, Baja Verapaz' },
  { id: 42, label: 'San Jerónimo, Baja Verapaz' },
  { id: 43, label: 'Chiquimula, Chiquimula' },
  { id: 44, label: 'Camotán, Chiquimula' },
  { id: 45, label: 'Concepción Las Minas, Chiquimula' },
  { id: 46, label: 'Esquipulas, Chiquimula' },
  { id: 47, label: 'Ipala, Chiquimula' },
  { id: 48, label: 'Jocotán, Chiquimula' },
  { id: 49, label: 'Olopa, Chiquimula' },
  { id: 50, label: 'Quezaltepeque, Chiquimula' },
  { id: 51, label: 'San José La Arada, Chiquimula' },
  { id: 52, label: 'San Juan Ermita, Chiquimula' },
  { id: 53, label: 'San Jacinto, Chiquimula' },
  { id: 54, label: 'Guastatoya, El Progreso' },
  { id: 55, label: 'Morazán, El Progreso' },
  { id: 56, label: 'San Agustín Acasaguastlán, El Progreso' },
  { id: 57, label: 'San Cristóbal Acasaguastlán, El Progreso' },
  { id: 58, label: 'El Jícaro, El Progreso' },
  { id: 59, label: 'Sansare, El Progreso' },
  { id: 60, label: 'Sanarate, El Progreso' },
  { id: 61, label: 'San Antonio La Paz, El Progreso' },
  { id: 62, label: 'Puerto Barrios, Izabal' },
  { id: 63, label: 'Livingston, Izabal' },
  { id: 64, label: 'El Estor, Izabal' },
  { id: 65, label: 'Morales, Izabal' },
  { id: 66, label: 'Los Amates, Izabal' },
  { id: 67, label: 'Cabañas, Zacapa' },
  { id: 68, label: 'Estanzuela, Zacapa' },
  { id: 69, label: 'Gualán, Zacapa' },
  { id: 70, label: 'Huité, Zacapa' },
  { id: 71, label: 'La Unión, Zacapa' },
  { id: 72, label: 'Río Hondo, Zacapa' },
  { id: 73, label: 'San Diego, Zacapa' },
  { id: 74, label: 'Teculután, Zacapa' },
  { id: 75, label: 'Usumatlán, Zacapa' },
  { id: 76, label: 'Zacapa, Zacapa' },
  { id: 77, label: 'Jalapa, Jalapa' },
  { id: 78, label: 'San Pedro Pinula, Jalapa' },
  { id: 79, label: 'San Luis Jilotepeque, Jalapa' },
  { id: 80, label: 'San Manuel Chaparrón, Jalapa' },
  { id: 81, label: 'San Carlos Alzatate, Jalapa' },
  { id: 82, label: 'Monjas, Jalapa' },
  { id: 83, label: 'Mataquescuintla, Jalapa' },
  { id: 84, label: 'Jutiapa, Jutiapa' },
  { id: 85, label: 'Agua Blanca, Jutiapa' },
  { id: 86, label: 'Asunción Mita, Jutiapa' },
  { id: 87, label: 'Atescatempa, Jutiapa' },
  { id: 88, label: 'Comapa, Jutiapa' },
  { id: 89, label: 'Conguaco, Jutiapa' },
  { id: 90, label: 'El Adelanto, Jutiapa' },
  { id: 91, label: 'El Progreso, Jutiapa' },
  { id: 92, label: 'Jalpatagua, Jutiapa' },
  { id: 93, label: 'Jeréz, Jutiapa' },
  { id: 94, label: 'Moyuta, Jutiapa' },
  { id: 95, label: 'Pasaco, Jutiapa' },
  { id: 96, label: 'Quesada, Jutiapa' },
  { id: 97, label: 'San José Acatempa, Jutiapa' },
  { id: 98, label: 'Santa Catarina Mita, Jutiapa' },
  { id: 99, label: 'Yupiltepeque, Jutiapa' },
  { id: 100, label: 'Zapotitlán, Jutiapa' },
  { id: 101, label: 'Cuilapa, Santa Rosa' },
  { id: 102, label: 'Casillas, Santa Rosa' },
  { id: 103, label: 'Chiquimulilla, Santa Rosa' },
  { id: 104, label: 'Guazacapán, Santa Rosa' },
  { id: 105, label: 'Nueva Santa Rosa' },
  { id: 106, label: 'Oratorio, Santa Rosa' },
  { id: 107, label: 'Pueblo Nuevo Viñas, Santa Rosa' },
  { id: 108, label: 'San Juan Tecuaco, Santa Rosa' },
  { id: 109, label: 'San Rafaél Las Flores, Santa Rosa' },
  { id: 110, label: 'Santa Cruz Naranjo, Santa Rosa' },
  { id: 111, label: 'Santa María Ixhuatán, Santa Rosa' },
  { id: 112, label: 'Santa Rosa de Lima, Santa Rosa' },
  { id: 113, label: 'Taxisco, Santa Rosa' },
  { id: 114, label: 'Barberena, Santa Rosa' },
  { id: 115, label: 'Chimaltenango, Chimaltenango' },
  { id: 116, label: 'San José Poaquíl, Chimaltenango' },
  { id: 117, label: 'San Martín Jilotepeque, Chimaltenango' },
  { id: 118, label: 'San Juan Comalapa, Chimaltenango' },
  { id: 119, label: 'Santa Apolonia, Chimaltenango' },
  { id: 120, label: 'Tecpán Guatemala, Chimaltenango' },
  { id: 121, label: 'Patzún, Chimaltenango' },
  { id: 122, label: 'Pochuta, Chimaltenango' },
  { id: 123, label: 'Patzicía, Chimaltenango' },
  { id: 124, label: 'Santa Cruz Balanyá, Chimaltenango' },
  { id: 125, label: 'Acatenango, Chimaltenango' },
  { id: 126, label: 'San Pedro Yepocapa, Chimaltenango' },
  { id: 127, label: 'San Andrés Itzapa, Chimaltenango' },
  { id: 128, label: 'Parramos, Chimaltenango' },
  { id: 129, label: 'Zaragoza, Chimaltenango' },
  { id: 130, label: 'El Tejar, Chimaltenango' },
  { id: 131, label: 'Escuintla, Escuintla' },
  { id: 132, label: 'Guanagazapa, Escuintla' },
  { id: 133, label: 'Iztapa, Escuintla' },
  { id: 134, label: 'La Democracia, Escuintla' },
  { id: 135, label: 'La Gomera, Escuintla' },
  { id: 136, label: 'Masagua, Escuintla' },
  { id: 137, label: 'Nueva Concepción, Escuintla' },
  { id: 138, label: 'Palín, Escuintla' },
  { id: 139, label: 'Puerto San José, Escuintla' },
  { id: 140, label: 'San Vicente Pacaya, Escuintla' },
  { id: 141, label: 'Santa Lucía Cotzumalguapa, Escuintla' },
  { id: 142, label: 'Siquinalá, Escuintla' },
  { id: 143, label: 'Tiquisate, Escuintla' },
  { id: 144, label: 'Alotenango, Sacatepéquez' },
  { id: 145, label: 'Antigua Guatemala, Sacatepéquez' },
  { id: 146, label: 'Ciudad Vieja, Sacatepéquez' },
  { id: 147, label: 'Jocotenango, Sacatepéquez' },
  { id: 148, label: 'Magdalena Milpas Altas, Sacatepéquez' },
  { id: 149, label: 'Pastores, Sacatepéquez' },
  { id: 150, label: 'San Antonio Aguas Calientes, Sacatepéquez' },
  { id: 151, label: 'San Bartolomé Milpas Altas, Sacatepéquez' },
  { id: 152, label: 'San Lucas Sacatepéquez, Sacatepéquez' },
  { id: 153, label: 'San Miguel Dueñas, Sacatepéquez' },
  { id: 154, label: 'Santa Catarina Barahona, Sacatepéquez' },
  { id: 155, label: 'Santa Lucía Milpas Altas, Sacatepéquez' },
  { id: 156, label: 'Santa María de Jesús, Sacatepéquez' },
  { id: 157, label: 'Santiago Sacatepéquez, Sacatepéquez' },
  { id: 158, label: 'Santo Domingo Xenacoj, Sacatepéquez' },
  { id: 159, label: 'Sumpango, Sacatepéquez' },
  { id: 160, label: 'Champerico, Retalhuleu' },
  { id: 161, label: 'El Asintal, Retalhuleu' },
  { id: 162, label: 'Nuevo San Carlos, Retalhuleu' },
  { id: 163, label: 'Retalhuleu, Retalhuleu' },
  { id: 164, label: 'San Andrés Villa Seca, Retalhuleu' },
  { id: 165, label: 'San Martín Zapotitlán, Retalhuleu' },
  { id: 166, label: 'San Felipe, Retalhuleu' },
  { id: 167, label: 'San Sebastián, Retalhuleu' },
  { id: 168, label: 'Santa Cruz Muluá, Retalhuleu' },
  { id: 169, label: 'San Marcos, San Marcos' },
  { id: 170, label: 'Ayutla, San Marcos' },
  { id: 171, label: 'Catarina, San Marcos' },
  { id: 172, label: 'Comitancillo, San Marcos' },
  { id: 173, label: 'Concepción Tutuapa, San Marcos' },
  { id: 174, label: 'El Quetzal, San Marcos' },
  { id: 175, label: 'El Rodeo, San Marcos' },
  { id: 176, label: 'El Tumbador, San Marcos' },
  { id: 177, label: 'Ixchiguán, San Marcos' },
  { id: 178, label: 'La Reforma, San Marcos' },
  { id: 179, label: 'Malacatán, San Marcos' },
  { id: 180, label: 'Nuevo Progreso, San Marcos' },
  { id: 181, label: 'Ocós, San Marcos' },
  { id: 182, label: 'Pajapita, San Marcos' },
  { id: 183, label: 'Esquipulas Palo Gordo, San Marcos' },
  { id: 184, label: 'San Antonio Sacatepéquez, San Marcos' },
  { id: 185, label: 'San Cristóbal Cucho, San Marcos' },
  { id: 186, label: 'San José Ojetenam, San Marcos' },
  { id: 187, label: 'San Lorenzo, San Marcos' },
  { id: 188, label: 'San Miguel Ixtahuacán, San Marcos' },
  { id: 189, label: 'San Pablo, San Marcos' },
  { id: 190, label: 'San Pedro Sacatepéquez, San Marcos' },
  { id: 191, label: 'San Rafaél Pie de La Cuesta, San Marcos' },
  { id: 192, label: 'Sibinal, San Marcos' },
  { id: 193, label: 'Sipacapa, San Marcos' },
  { id: 194, label: 'Tacaná, San Marcos' },
  { id: 195, label: 'Tajumulco, San Marcos' },
  { id: 196, label: 'Tejutla, San Marcos' },
  { id: 197, label: 'Río Blanco, San Marcos' },
  { id: 198, label: 'Sololá, Sololá' },
  { id: 199, label: 'Concepción, Sololá' },
  { id: 200, label: 'Nahualá, Sololá' },
  { id: 201, label: 'Panajachel, Sololá' },
  { id: 202, label: 'San Andrés Semetabaj, Sololá' },
  { id: 203, label: 'San Antonio Palopó, Sololá' },
  { id: 204, label: 'San José Chacayá, Sololá' },
  { id: 205, label: 'San Juan La Laguna, Sololá' },
  { id: 206, label: 'San Lucas Tolimán, Sololá' },
  { id: 207, label: 'San Marcos La Laguna, Sololá' },
  { id: 208, label: 'San Pablo La Laguna, Sololá' },
  { id: 209, label: 'San Pedro La Laguna, Sololá' },
  { id: 210, label: 'Santa Catarina Ixtahuacan, Sololá' },
  { id: 211, label: 'Santa Catarina Palopó, Sololá' },
  { id: 212, label: 'Santa Clara La Laguna, Sololá' },
  { id: 213, label: 'Santa Cruz La Laguna, Sololá' },
  { id: 214, label: 'Santa Lucía Utatlán, Sololá' },
  { id: 215, label: 'Santa María Visitación, Sololá' },
  { id: 216, label: 'Santiago Atitlán, Sololá' },
  { id: 217, label: 'Mazatenango, Suchitepéquez' },
  { id: 218, label: 'Chicacao, Suchitepéquez' },
  { id: 219, label: 'Cuyotenango, Suchitepéquez' },
  { id: 220, label: 'Patulul, Suchitepéquez' },
  { id: 221, label: 'Pueblo Nuevo, Suchitepéquez' },
  { id: 222, label: 'Río Bravo, Suchitepéquez' },
  { id: 223, label: 'Samayac, Suchitepéquez' },
  { id: 224, label: 'San Antonio Suchitepéquez, Suchitepéquez' },
  { id: 225, label: 'San Bernardino, Suchitepéquez' },
  { id: 226, label: 'San José El Ídolo, Suchitepéquez' },
  { id: 227, label: 'San Francisco Zapotitlán, Suchitepéquez' },
  { id: 228, label: 'San Gabriel, Suchitepéquez' },
  { id: 229, label: 'San Juan Bautista, Suchitepéquez' },
  { id: 230, label: 'San Lorenzo, Suchitepéquez' },
  { id: 231, label: 'San Miguel Panán, Suchitepéquez' },
  { id: 232, label: 'San Pablo Jocopilas, Suchitepéquez' },
  { id: 233, label: 'Santa Barbara, Suchitepéquez' },
  { id: 234, label: 'Santo Domingo Suchitepequez, Suchitepéquez' },
  { id: 235, label: 'Santo Tomas La Unión, Suchitepéquez' },
  { id: 236, label: 'Zunilito, Suchitepéquez' },
  { id: 237, label: 'Totonicapán, Totonicapán' },
  { id: 238, label: 'Momostenango, Totonicapán' },
  { id: 239, label: 'San Andrés Xecul, Totonicapán' },
  { id: 240, label: 'San Bartolo, Totonicapán' },
  { id: 241, label: 'San Cristóbal, Totonicapán' },
  { id: 242, label: 'San Francisco El Alto, Totonicapán' },
  { id: 243, label: 'Santa Lucía La Reforma, Totonicapán' },
  { id: 244, label: 'Santa María Chiquimula, Totonicapán' },
  { id: 245, label: 'Almolonga, Quetzaltenango' },
  { id: 246, label: 'Cabricán, Quetzaltenango' },
  { id: 247, label: 'Cajolá, Quetzaltenango' },
  { id: 248, label: 'Cantel, Quetzaltenango' },
  { id: 249, label: 'Coatepeque, Quetzaltenango' },
  { id: 250, label: 'Colomba, Quetzaltenango' },
  { id: 251, label: 'Concepción Chiquirichapa, Quetzaltenango' },
  { id: 252, label: 'El Palmar, Quetzaltenango' },
  { id: 253, label: 'Flores Costa Cuca, Quetzaltenango' },
  { id: 254, label: 'Génova, Quetzaltenango' },
  { id: 255, label: 'Huitán, Quetzaltenango' },
  { id: 256, label: 'La Esperanza, Quetzaltenango' },
  { id: 257, label: 'Olintepeque, Quetzaltenango' },
  { id: 258, label: 'San Juan Ostuncalco, Quetzaltenango' },
  { id: 259, label: 'Palestina de Los Altos, Quetzaltenango' },
  { id: 260, label: 'Quetzaltenango, Quetzaltenango' },
  { id: 261, label: 'Salcajá, Quetzaltenango' },
  { id: 262, label: 'San Carlos Sija, Quetzaltenango' },
  { id: 263, label: 'San Francisco La Unión, Quetzaltenango' },
  { id: 264, label: 'San Martín Sacatepéquez, Quetzaltenango' },
  { id: 265, label: 'San Mateo, Quetzaltenango' },
  { id: 266, label: 'San Miguel Sigüilá, Quetzaltenango' },
  { id: 267, label: 'Sibilia, Quetzaltenango' },
  { id: 268, label: 'Zunil, Quetzaltenango' },
];

export default deparments;
