export const GET_RECEIPT_SETTLEMENT_INIT_REQUEST = '[RECEIPT-SETTLEMENT APP] GET RECEIPT SETTLEMENT INIT_REQUEST';
export const GET_RECEIPT_SETTLEMENT_SUCCESS = '[RECEIPT-SETTLEMENT APP] GET RECEIPT SETTLEMENT SUCCESS';
export const GET_RECEIPT_SETTLEMENT_FAILURE = '[RECEIPT-SETTLEMENT APP] GET RECEIPT SETTLEMENT FAILURE';

export const GET_FEES_RECEIPT_SETTLEMENT_INIT_REQUEST = '[RECEIPT-SETTLEMENT APP] GET FEES RECEIPT SETTLEMENT INIT_REQUEST';
export const GET_FEES_RECEIPT_SETTLEMENT_SUCCESS = '[RECEIPT-SETTLEMENT APP] GET FEES RECEIPT SETTLEMENT SUCCESS';
export const GET_FEES_RECEIPT_SETTLEMENT_FAILURE = '[RECEIPT-SETTLEMENT APP] GET FEES RECEIPT SETTLEMENT FAILURE';

export const SAVE_RECEIPT_SETTLEMENT_INIT_REQUEST = '[RECEIPT-SETTLEMENT APP] SAVE RECEIPT SETTLEMENT INIT_REQUEST';
export const SAVE_RECEIPT_SETTLEMENT_SUCCESS = '[RECEIPT-SETTLEMENT APP] SAVE RECEIPT SETTLEMENT SUCCESS';
export const SAVE_RECEIPT_SETTLEMENT_FAILURE = '[RECEIPT-SETTLEMENT APP] SAVE RECEIPT SETTLEMENT FAILURE';

export const NEW_RECEIPT_SETTLEMENT = '[RECEIPT-SETTLEMENT APP] NEW RECEIPT SETTLEMENT';

export const OPEN_CREATE_RECEIPT_SETTLEMENT_DIALOG = '[RECEIPT-SETTLEMENT APP] OPEN CREATE RECEIPT SETTLEMENT DIALOG';
export const CLOSE_CREATE_RECEIPT_SETTLEMENT_DIALOG = '[RECEIPT-SETTLEMENT APP] CLOSE RECEIPT SETTLEMENT DIALOG';
export const OPEN_EDIT_RECEIPT_SETTLEMENT_DIALOG = '[RECEIPT-SETTLEMENT APP] OPEN EDIT RECEIPT SETTLEMENT DIALOG';
export const DELETE_RECEIPT_SETTLEMENT = '[RECEIPT-SETTLEMENT APP] DELETE RECEIPT SETTLEMENT';
export const CREATE_RECEIPT_SETTLEMENT = '[RECEIPT-SETTLEMENT APP] CREATE RECEIPT SETTLEMENT';
