export const GET_RECEIPT_SETTLEMENTS_INIT_REQUEST = '[RECEIPT SETTLEMENTS APP] GET RECEIPT SETTLEMENTS INIT REQUEST';
export const GET_RECEIPT_SETTLEMENTS_SUCCESS = '[RECEIPT SETTLEMENTS APP] GET RECEIPT SETTLEMENTS SUCCESS';
export const GET_RECEIPT_SETTLEMENTS_FAILURE = '[RECEIPT SETTLEMENTS APP] GET RECEIPT SETTLEMENTS FAILURE';

export const SET_RECEIPT_SETTLEMENTS_SEARCH_TEXT = '[RECEIPT SETTLEMENTS APP] SET RECEIPT SETTLEMENTS SEARCH TEXT';

export const OPEN_CHANGE_STATE_RECEIPT_SETTLEMENTS_DIALOG = '[RECEIPT SETTLEMENTS APP] OPEN CHANGE STATE RECEIPT SETTLEMENTS DIALOG';
export const CLOSE_CHANGE_STATE_RECEIPT_SETTLEMENTS_DIALOG = '[RECEIPT SETTLEMENTS APP] CLOSE CHANGE STATE RECEIPT SETTLEMENTS DIALOG';

export const CHANGE_RECEIPT_SETTLEMENTS_STATUS_INIT = '[RECEIPT SETTLEMENTS APP] CHANGE RECEIPT SETTLEMENTS STATUS INIT';
export const CHANGE_RECEIPT_SETTLEMENTS_STATUS_SUCCESS = '[RECEIPT SETTLEMENTS APP] CHANGE RECEIPT SETTLEMENTS STATUS SUCCESS';
export const CHANGE_RECEIPT_SETTLEMENTS_STATUS_FAILURE = '[RECEIPT SETTLEMENTS APP] CHANGE RECEIPT SETTLEMENTS STATUS FAILURE';

export const GET_RECEIPT_SETTLEMENTS_STATUS_FLOW = '[RECEIPT SETTLEMENTS APP] GET STATUS FLOW';

export const OPEN_REPORT_RECEIPT_SETTLEMENTS_DIALOG = '[RECEIPT SETTLEMENTS APP] OPEN REPORT RECEIPT SETTLEMENTS DIALOG';
export const CLOSE_REPORT_RECEIPT_SETTLEMENTS_DIALOG = '[RECEIPT SETTLEMENTS APP] CLOSE REPORT RECEIPT SETTLEMENTS DIALOG';
export const GET_REPORT_RECEIPT_SETTLEMENT_INIT_REQUEST = '[RECEIPT SETTLEMENTS APP] GET REPORT RECEIPT SETTLEMENTS INIT REQUEST';
export const GET_REPORT_RECEIPT_SETTLEMENT_SUCCESS = '[RECEIPT SETTLEMENTS APP] GET REPORT RECEIPT SETTLEMENTS SUCCESS';
export const GET_REPORT_RECEIPT_SETTLEMENT_FAILURE = '[RECEIPT SETTLEMENTS APP] GET REPORT RECEIPT SETTLEMENTS FAILURE';
