export const SET_EMPLOYEES_SEARCH_TEXT = '[FILE-RECORDS APP] SET EMPLOYEES SEARCH TEXT';
export const GET_EMPLOYEES_INIT_REQUEST = '[EMPLOYEES APP] GET EMPLOYEES INIT REQUEST';
export const GET_EMPLOYEES_SUCCESS = '[EMPLOYEES APP] GET EMPLOYEES SUCCESS';
export const GET_EMPLOYEES_FAILURE = '[EMPLOYEES APP] GET EMPLOYEES FAILURE';
export const DELETE_EMPLOYEE = '[EMPLOYEES APP] DELETE EMPLOYEE';
