export const SAVE_PROCTOR_AGENDA_INIT_REQUEST = '[PROCTOR_AGENDA APP] SAVE PROCTOR_AGENDA INIT REQUEST';
export const SAVE_PROCTOR_AGENDA_SUCCESS = '[PROCTOR_AGENDA APP] SAVE PROCTOR_AGENDA SUCCESS';
export const SAVE_PROCTOR_AGENDA_FAILURE = '[PROCTOR_AGENDA APP] SAVE PROCTOR_AGENDA FAILURE';

export const UPDATE_PROCTOR_AGENDA_INIT_REQUEST = '[PROCTOR_AGENDA APP] UPDATE PROCTOR_AGENDA INIT REQUEST';
export const UPDATE_PROCTOR_AGENDA_SUCCESS = '[PROCTOR_AGENDA APP] UPDATE PROCTOR_AGENDA SUCCESS';
export const UPDATE_PROCTOR_AGENDA_FAILURE = '[PROCTOR_AGENDA APP] UPDATE PROCTOR_AGENDA FAILURE';

export const NEW_PROCTOR_AGENDA = '[PROCTOR_AGENDA APP] NEW PROCTOR_AGENDA';

export const GET_PROCTOR_AGENDA_INIT_REQUEST = '[PROCTOR_AGENDA APP] GET PROCTOR_AGENDA INIT REQUEST';
export const GET_PROCTOR_AGENDA_SUCCESS = '[PROCTOR_AGENDA APP] GET PROCTOR_AGENDA SUCCESS';
export const GET_PROCTOR_AGENDA_FAILURE = '[PROCTOR_AGENDA APP] GET PROCTOR_AGENDA FAILURE';

export const OPEN_ADD_CASE_ACTIVITY_DIALOG = '[PROCTOR_AGENDA APP] OPEN ADD CASE ACTIVITY DIALOG';
export const CLOSE_ADD_CASE_ACTIVITY_DIALOG = '[PROCTOR_AGENDA APP] CLOSE ADD CASE ACTIVITY DIALOG';
export const ASSIGN_CASE_ACTIVITIES = '[PROCTOR_AGENDA APP] ASSIGN CASE ACTIVITIES';
export const REMOVE_CASE_ACTIVITY = '[PROCTOR_AGENDA APP] REMOVE CASE ACTIVITY';
export const OPEN_CHANGE_ACTIVITY_STATE_DIALOG = '[PROCTOR-AGENDA APP] OPEN CHANGE ACTIVITY_STATE DIALOG';
export const CLOSE_CHANGE_ACTIVITY_STATE_DIALOG = '[PROCTOR-AGENDA APP] CLSE CHANGE ACTIVITY_STATE DIALOG';

export const CHANGE_ACTIVITY_RECORD_STATUS_INIT_REQUEST = '[PROCTOR-AGENDA APP] CHANGE ACTIVITY_RECORD STATUS INIT REQUEST';
export const CHANGE_ACTIVITY_RECORD_STATUS_SUCCESS = '[PROCTOR-AGENDA APP] CHANGE ACTIVITY_RECORD STATUS SUCCESS';
export const CHANGE_ACTIVITY_RECORD_STATUS_FAILURE = '[PROCTOR-AGENDA APP] CHANGE ACTIVITY_RECORD STATUS FAILURE';

export const OPEN_ADD_ACTIVITY_SETTLE_DIALOG = '[PROCTOR-AGENDA APP] OPEN ADD ACTIVITY SETTLEMENT DIALOG';
export const CLOSE_ADD_ACTIVITY_SETTLE_DIALOG = '[PROCTOR-AGENDA APP] OPEN CLOSE ACTIVITY SETTLEMENT DIALOG';

export const ADD_ACTIVITY_SETTLE_INIT_REQUEST = '[PROCTOR-AGENDA APP] ADD ACTIVITY SETTLE INIT REQUEST';
export const ADD_ACTIVITY_SETTLE_SUCCESS = '[PROCTOR-AGENDA APP] ADD ACTIVITY SETTLE SUCCESS';
export const ADD_ACTIVITY_SETTLE_FAILURE = '[PROCTOR-AGENDA APP] ADD ACTIVITY SETTLE FAILURE';

export const GET_ACTIVITY_SETTLE = '[PROCTOR-AGENDA APP] GET ACTIVITY SETTLE';
export const DELETE_ACTIVITY_SETTLE = '[PROCTOR-AGENDA APP] DELETE ACTIVITY SETTLE';

export const RELOAD_DATA = '[PROCTOR-AGENDA APP] RELOAD_DATA';