export const SET_PROCTOR_AGENDA_SEARCH_CRITERIA = '[PROCTOR-AGENDA APP] SET PROCTOR AGENDA SEARCH CRITERIA';
export const GET_PROCTOR_AGENDA_INIT_REQUEST = '[PROCTOR-AGENDA APP] GET PROCTOR AGENDA INIT REQUEST';
export const GET_PROCTOR_AGENDA_SUCCESS = '[PROCTOR-AGENDA APP] GET PROCTOR AGENDA SUCCESS';
export const GET_PROCTOR_AGENDA_FAILURE = '[PROCTOR-AGENDA APP] GET PROCTOR AGENDA FAILURE';

export const OPEN_CHANGE_STATE_DIALOG = '[PROCTOR-AGENDA APP] OPEN CHANGE STATE DIALOG';
export const CLOSE_CHANGE_STATE_DIALOG = '[PROCTOR-AGENDA APP] CLSE CHANGE STATE DIALOG';

export const OPEN_GET_ASSIGNED_ACTIVITIES_DIALOG = '[PROCTOR-AGENDA APP] OPEN GET ASSIGNED ACTIVITIES DIALOG';
export const CLOSE_GET_ASSIGNED_ACTIVITIES_DIALOG = '[PROCTOR-AGENDA APP] CLOSE GET ASSIGNED ACTIVITIES DIALOG';

export const CHANGE_AGENDA_STATUS_INIT_REQUEST = '[PROCTOR-AGENDA APP] CHANGE AGENDA STATUS INIT REQUEST';
export const CHANGE_AGENDA_STATUS_SUCCESS = '[PROCTOR-AGENDA APP] CHANGE AGENDA STATUS SUCCESS';
export const CHANGE_AGENDA_STATUS_FAILURE = '[PROCTOR-AGENDA APP] CHANGE AGENDA STATUS FAILURE';
