export const SET_INITIAL_DATA = '[CONTACTS APP] SET INITIAL DATA';
export const CREATE_CONTACT = '[CONTACTS APP] CREATE OR MODIFY CONTACT';
export const DELETE_CONTACT = '[CONTACTS APP] DELETE CONTACT';

export const OPEN_CREATE_CONTACT_DIALOG = '[CONTACTS APP] OPEN CREATE CONTACT DIALOG';
export const CLOSE_CREATE_CONTACT_DIALOG = '[CONTACTS APP] CLOSE CREATE CONTACT DIALOG';
export const OPEN_EDIT_CONTACT_DIALOG = '[CONTACTS APP] OPEN EDIT CONTACT DIALOG';
export const CLOSE_EDIT_CONTACT_DIALOG = '[CONTACTS APP] CLOSE EDIT CONTACT DIALOG';
