package com.bufete.backend.util;

public interface RoleConstants {

  String USUARIO_ADMIN = "ROLE_USUARIO_ADMIN";
  
  // EMPLOYEES

  String EMPLEADO_LECTURA = "ROLE_EMPLEADO_LECTURA";
  String EMPLEADO_CREA = "ROLE_EMPLEADO_CREA";
  String EMPLEADO_ELIMINA = "ROLE_EMPLEADO_ELIMINA";

  // CURRENCY

  String MONEDA_LECTURA = "ROLE_MONEDA_LECTURA";
  String MONEDA_CREA = "ROLE_MONEDA_CREA";
  String MONEDA_MODIFICA = "ROLE_MONEDA_MODIFICA";
  String MONEDA_ELIMINA = "ROLE_MONEDA_ELIMINA";

  // COMPANY

  String EMPRESA_LECTURA = "ROLE_EMPRESA_LECTURA";
  String EMPRESA_CREA = "ROLE_EMPRESA_CREA";
  String EMPRESA_MODIFICA = "ROLE_EMPRESA_MODIFICA";
  String EMPRESA_ELIMINA = "ROLE_EMPRESA_ELIMINA";

  // ROL

  String ROL_LECTURA = "ROLE_ROL_LECTURA";
  String ROL_CREA = "ROLE_ROL_CREA";
  String ROL_MODIFICA = "ROLE_ROL_MODIFICA";
  String ROL_ELIMINA = "ROLE_ROL_ELIMINA";

  // USUARIO

  String USUARIO_LECTURA = "ROLE_USUARIO_LECTURA";
  String USUARIO_CREA = "ROLE_USUARIO_CREA";
  String USUARIO_ASIGNA_ROL = "ROLE_USUARIO_ASIGNA_ROL";
  String USUARIO_ELIMINA = "ROLE_USUARIO_ELIMINA";
  String USUARIO_ASIGNA = "ROLE_USUARIO_ASIGNA";
  String USUARIO_RESETEA = "ROLE_USUARIO_RESETEA";
  String USUARIO_LISTADO_EMPLEADOS = "ROLE_USUARIO_LISTADO_EMPLEADOS";

  // CLIENTE

  String CLIENTE_LECTURA = "ROLE_CLIENTE_LECTURA";
  String CLIENTE_CREA = "ROLE_CLIENTE_CREA";
  String CLIENTE_ELIMINA = "ROLE_CLIENTE_ELIMINA";

  // EXPEDIENTE

  String EXPEDIENTE_LECTURA = "ROLE_EXPEDIENTE_LECTURA";
  String EXPEDIENTE_CREA = "ROLE_EXPEDIENTE_CREA";
  String EXPEDIENTE_CAMBIA_ESTADO = "ROLE_EXPEDIENTE_CAMBIA_ESTADO";
  String EXPEDIENTE_EDITA = "ROLE_EXPEDIENTE_EDITA";
  String EXPEDIENTE_AUTORIZA = "ROLE_EXPEDIENTE_AUTORIZA_RECHAZA";
  String EXPEDIENTE_TIPO_LISTA = "ROLE_EXPEDIENTE_TIPO_LISTA";
  String EXPEDIENTE_SUBTIPO_LISTA = "ROLE_EXPEDIENTE_SUBTIPO_LISTA";
  String EXPEDIENTE_LISTADO_CLIENTES = "ROLE_EXPEDIENTE_LISTADO_CLIENTES";
  String EXPEDIENTE_LISTADO_EMPLEADOS = "ROLE_EXPEDIENTE_LISTADO_EMPLEADOS";
  String EXPEDIENTE_COMBINA_EXPEDIENTE = "ROLE_EXPEDIENTE_COMBINA_EXPEDIENTE";

  // ACTIVITY

  String ACTIVIDAD_LECTURA = "ROLE_ACTIVIDAD_LECTURA";
  String ACTIVIDAD_CREA = "ROLE_ACTIVIDAD_CREA";
  String ACTIVIDAD_MODIFICA = "ROLE_ACTIVIDAD_MODIFICA";
  String ACTIVIDAD_ELIMINA = "ROLE_ACTIVIDAD_ELIMINA";

  // INSTITUTION

  String INSTITUCION_LECTURA = "ROLE_INSTITUCION_LECTURA";
  String INSTITUCION_CREA = "ROLE_INSTITUCION_CREA";
  String INSTITUCION_MODIFICA = "ROLE_INSTITUCION_MODIFICA";
  String INSTITUCION_ELIMINA = "ROLE_INSTITUCION_ELIMINA";

  // FILE MANAGER

  String DOCUMENTO_LECTURA = "ROLE_DOCUMENTO_LECTURA";
  String DOCUMENTO_CREA = "ROLE_DOCUMENTO_CREA";
  String DOCUMENTO_ELIMINA = "ROLE_DOCUMENTO_ELIMINA";

  // CASE ACTIVITY

  String EXPEDIENTE_ACTIVIDAD_LECTURA = "ROLE_EXPEDIENTE_ACTIVIDAD_LECTURA";
  String EXPEDIENTE_ACTIVIDAD_CREA = "ROLE_EXPEDIENTE_ACTIVIDAD_CREA";
  String EXPEDIENTE_ACTIVIDAD_ELIMINA = "ROLE_EXPEDIENTE_ACTIVIDAD_ELIMINA";
  String EXPEDIENTE_ACTIVIDAD_LISTADO = "ROLE_EXPEDIENTE_ACTIVIDAD_LISTADO";
  String EXPEDIENTE_ACTIVIDAD_LISTADO_INSTITUCION = "ROLE_EXPEDIENTE_ACTIVIDAD_LISTADO_INSTITUCION";
  String EXPEDIENTE_ACTIVIDAD_LISTADO_EMPLEADOS = "ROLE_EXPEDIENTE_ACTIVIDAD_LISTADO_EMPLEADOS";
  String EXPEDIENTE_ACTIVIDAD_LISTADO_EXPEDIENTES = "ROLE_EXPEDIENTE_ACTIVIDAD_LISTADO_EXPEDIENTES";

  // APP CONFIG

  String CONFIGURACION_LECTURA = "ROLE_CONFIGURACION_LECTURA";
  String CONFIGURACION_CREA = "ROLE_CONFIGURACION_CREA";
  String CONFIGURACION_MODIFICA = "ROLE_CONFIGURACION_MODIFICA";
  String CONFIGURACION_ELIMINA = "ROLE_CONFIGURACION_ELIMINA";

  // CASE ACTIVITY

  String AGENDA_PROCURADOR_LECTURA = "ROLE_AGENDA_PROCURADOR_LECTURA";
  String AGENDA_PROCURADOR_CREA = "ROLE_AGENDA_PROCURADOR_CREA";
  String AGENDA_PROCURADOR_ELIMINA = "ROLE_AGENDA_PROCURADOR_ELIMINA";
  String AGENDA_PROCURADOR_EDITA = "ROLE_AGENDA_PROCURADOR_EDITA";
  String AGENDA_PROCURADOR_LIQUIDA = "ROLE_AGENDA_PROCURADOR_LIQUIDA";
  String AGENDA_PROCURADOR_CAMBIO_ESTADO = "ROLE_AGENDA_PROCURADOR_CAMBIO_ESTADO";
  String AGENDA_PROCURADOR_AUTORIZA = "ROLE_AGENDA_PROCURADOR_AUTORIZA";

  // ACTIVITY SETTLEMENT

  String AGENDA_LIQUIDACION_LECTURA = "ROLE_AGENDA_LIQUIDACION_LECTURA";
  String AGENDA_LIQUIDACION_CREA = "ROLE_AGENDA_LIQUIDACION_CREA";
  String AGENDA_LIQUIDACION_ELIMINA = "ROLE_AGENDA_LIQUIDACION_ELIMINA";

  // STAMP DUTY

  String TIMBRE_FISCAL_INVENTARIO_LECTURA = "ROLE_TIMBRE_FISCAL_INVENTARIO_LECTURA";
  String TIMBRE_FISCAL_INVENTARIO_CREA = "ROLE_TIMBRE_FISCAL_INVENTARIO_CREA";
  String TIMBRE_FISCAL_INVENTARIO_ELIMINA = "ROLE_TIMBRE_FISCAL_INVENTARIO_ELIMINA";
  String TIMBRE_FISCAL_INVENTARIO_CAMBIA_ESTADO = "ROLE_TIMBRE_FISCAL_INVENTARIO_CAMBIA_ESTADO";
  String TIMBRE_FISCAL_INVENTARIO_AUTORIZA = "ROLE_TIMBRE_FISCAL_INVENTARIO_AUTORIZA";
  String TIMBRE_FISCAL_INVENTARIO_EDITA = "ROLE_TIMBRE_FISCAL_INVENTARIO_EDITA";
  String TIMBRE_FISCAL_INVENTARIO_LISTADO_EXPEDIENTES = "ROLE_TIMBRE_FISCAL_INVENTARIO_LISTADO_EXPEDIENTES";
  String TIMBRE_FISCAL_INVENTARIO_LISTADO_PRODUCTO = "ROLE_TIMBRE_FISCAL_INVENTARIO_LISTADO_PRODUCTO";
  String TIMBRE_FISCAL_INVENTARIO_LISTADO_EMPLEADOS = "ROLE_TIMBRE_FISCAL_INVENTARIO_LISTADO_EMPLEADOS";

  // PRODUCT DUTY

  String PRODUCTO_LECTURA = "ROLE_PRODUCTO_LECTURA";
  String PRODUCTO_CREA = "ROLE_PRODUCTO_CREA";
  String PRODUCTO_ELIMINA = "ROLE_PRODUCTO_ELIMINA";

  // TIPO EXPEDIENTE

  String TIPO_EXPEDIENTE_LECTURA = "ROLE_TIPO_EXPEDIENTE_LECTURA";
  String TIPO_EXPEDIENTE_CREA = "ROLE_TIPO_EXPEDIENTE_CREA";
  String TIPO_EXPEDIENTE_MODIFICA = "ROLE_TIPO_EXPEDIENTE_MODIFICA";
  String TIPO_EXPEDIENTE_ELIMINA = "ROLE_TIPO_EXPEDIENTE_ELIMINA";

  // TIPO EXPEDIENTE

  String SUB_TIPO_EXPEDIENTE_LECTURA = "ROLE_SUB_TIPO_EXPEDIENTE_LECTURA";
  String SUB_TIPO_EXPEDIENTE_CREA = "ROLE_SUB_TIPO_EXPEDIENTE_CREA";
  String SUB_TIPO_EXPEDIENTE_MODIFICA = "ROLE_SUB_TIPO_EXPEDIENTE_MODIFICA";
  String SUB_TIPO_EXPEDIENTE_ELIMINA = "ROLE_SUB_TIPO_EXPEDIENTE_ELIMINA";

  // PROVEEDORES

  String PROVEEDOR_LECTURA = "ROLE_PROVEEDOR_LECTURA";
  String PROVEEDOR_CREA = "ROLE_PROVEEDOR_CREA";
  String PROVEEDOR_MODIFICA = "ROLE_PROVEEDOR_MODIFICA";
  String PROVEEDOR_ELIMINA = "ROLE_PROVEEDOR_ELIMINA";

  // CONCEPTOS

  String CONCEPTO_LECTURA = "ROLE_CONCEPTO_LECTURA";
  String CONCEPTO_CREA = "ROLE_CONCEPTO_CREA";
  String CONCEPTO_MODIFICA = "ROLE_CONCEPTO_MODIFICA";
  String CONCEPTO_ELIMINA = "ROLE_CONCEPTO_ELIMINA";

  // GASTOS

  String DOCUMENTOS_GASTOS_LECTURA = "ROLE_DOCUMENTOS_GASTOS_LECTURA";
  String DOCUMENTOS_GASTOS_CREA = "ROLE_DOCUMENTOS_GASTOS_CREA";
  String DOCUMENTOS_GASTOS_CAMBIA_ESTADO = "ROLE_DOCUMENTOS_GASTOS_CAMBIA_ESTADO";
  String DOCUMENTOS_GASTOS_AUTORIZA = "ROLE_DOCUMENTOS_GASTOS_AUTORIZA";
  String DOCUMENTOS_GASTOS_PROVEEDORES = "ROLE_DOCUMENTOS_GASTOS_PROVEEDORES";
  String DOCUMENTOS_GASTOS_CONCEPTOS = "ROLE_DOCUMENTOS_GASTOS_CONCEPTOS";
  String DOCUMENTOS_GASTOS_LISTADO_EXPEDIENTES = "ROLE_DOCUMENTOS_GASTOS_LISTADO_EXPEDIENTES";


  // LIQUIDACION DE FACTURA

  String LIQUIDACION_FACTURA_LECTURA = "ROLE_LIQUIDACION_FACTURA_LECTURA";
  String LIQUIDACION_FACTURA_CREA = "ROLE_LIQUIDACION_FACTURA_CREA";
  String LIQUIDACION_FACTURA_CAMBIA_ESTADO = "ROLE_LIQUIDACION_FACTURA_CAMBIA_ESTADO";
  String LIQUIDACION_FACTURA_AUTORIZA = "ROLE_LIQUIDACION_FACTURA_AUTORIZA";
  String LIQUIDACION_FACTURA_GENERAR_REPORTE = "ROLE_LIQUIDACION_FACTURA_GENERAR_REPORTE";
  String LIQUIDACION_FACTURA_GENERAR_FACTURA = "ROLE_LIQUIDACION_FACTURA_GENERAR_FACTURA";
  String LIQUIDACION_FACTURA_LISTADO_CLIENTES = "ROLE_LIQUIDACION_FACTURA_LISTADO_CLIENTES";

  // FACTURA

  String FACTURA_LECTURA = "ROLE_FACTURA_LECTURA";
  String FACTURA_CREA = "ROLE_FACTURA_CREA";
  String FACTURA_CAMBIA_ESTADO = "ROLE_FACTURA_CAMBIA_ESTADO";
  String FACTURA_AUTORIZA = "ROLE_FACTURA_AUTORIZA";
  String REPORTES_FACTURA_MENU = "ROLE_REPORTES_FACTURA_MENU";
  String LISTADO_FACTURA_MENU = "ROLE_LISTADO_FACTURA_MENU";
  String FACTURA_LISTADO_CLIENTES = "ROLE_FACTURA_LISTADO_CLIENTES";
  String FACTURA_LISTADO_DIRECCIONES = "ROLE_FACTURA_LISTADO_DIRECCIONES";
  String FACTURA_LISTADO_SERIES = "ROLE_FACTURA_LISTADO_SERIES";

  // SERIE FACTURA

  String SERIE_FACTURA_LECTURA = "ROLE_SERIE_FACTURA_LECTURA";
  String SERIE_FACTURA_CREA = "ROLE_SERIE_FACTURA_CREA";
  String SERIE_FACTURA_CAMBIA_ESTADO = "ROLE_SERIE_FACTURA_CAMBIA_ESTADO";

  // NOMENCLATURA CONTABLE

  String NOMENCLATURA_CONTABLE_LECTURA = "ROLE_NOMENCLATURA_CONTABLE_LECTURA";
  String NOMENCLATURA_CONTABLE_CREA = "ROLE_NOMENCLATURA_CONTABLE_CREA";
  String NOMENCLATURA_CONTABLE_CAMBIA_ESTADO = "ROLE_NOMENCLATURA_CONTABLE_CAMBIA_ESTADO";

  // RECIBO FACTURAS

  String RECIBO_FACTURA_LECTURA = "ROLE_RECIBO_FACTURA_LECTURA";
  String RECIBO_FACTURA_CREA = "ROLE_RECIBO_FACTURA_CREA";
  String RECIBO_FACTURA_MODIFICA = "ROLE_RECIBO_FACTURA_MODIFICA";
  String RECIBO_FACTURA_CAMBIA_ESTADO = "ROLE_RECIBO_FACTURA_CAMBIA_ESTADO";

  // BANCOS

  String BANCO_LECTURA = "ROLE_BANCO_LECTURA";
  String BANCO_CREA = "ROLE_BANCO_CREA";

  // TIPOS TRANSACCION

  String TIPO_TRANSACCION_LECTURA = "ROLE_TIPO_TRANSACCION_LECTURA";
  String TIPO_TRANSACCION_CREA = "ROLE_TIPO_TRANSACCION_CREA";
}