export const GET_EXPENSES_INIT_REQUEST = '[EXPENSES APP] GET EXPENSES INIT REQUEST';
export const GET_EXPENSES_SUCCESS = '[EXPENSES APP] GET EXPENSES SUCCESS';
export const GET_EXPENSES_FAILURE = '[EXPENSES APP] GET EXPENSES FAILURE';
export const OPEN_CHANGE_STATE_DIALOG = '[EXPENSES APP] OPEN CHANGE STATE DIALOG';
export const CLOSE_CHANGE_STATE_DIALOG = '[EXPENSES APP] CLOSE CHANGE STATE DIALOG';
export const SET_EXPENSES_SEARCH_TEXT = '[EXPENSES APP] SET EXPENSES SEARCH TEXT';

export const CHANGE_EXPENSE_STATUS_INIT = '[EXPENSES APP] CHANGE RECORD STATUS INIT';
export const CHANGE_EXPENSE_STATUS_SUCCESS = '[EXPENSES APP] CHANGE RECORD STATUS SUCCESS';
export const CHANGE_EXPENSE_STATUS_FAILURE = '[EXPENSES APP] CHANGE RECORD STATUS FAILURE';
