export const GET_EXPENSE_INIT_REQUEST = '[EXPENSE APP] GET EXPENSE INIT_REQUEST';
export const GET_EXPENSE_SUCCESS = '[EXPENSE APP] GET EXPENSE SUCCESS';
export const GET_EXPENSE_FAILURE = '[EXPENSE APP] GET EXPENSE FAILURE';

export const SAVE_EXPENSE_INIT_REQUEST = '[EXPENSE APP] SAVE EXPENSE INIT_REQUEST';
export const SAVE_EXPENSE_SUCCESS = '[EXPENSE APP] SAVE EXPENSE SUCCESS';
export const SAVE_EXPENSE_FAILURE = '[EXPENSE APP] SAVE EXPENSE FAILURE';

export const NEW_EXPENSE = '[EXPENSE APP] NEW EXPENSE';
