export const SET_INITIAL_DATA = '[EXPENSES-DETAIL APP] SET INITIAL DATA';
export const CREATE_EXPENSE_DETAILS = '[EXPENSES-DETAIL APP] CREATE OR MODIFY EXPENSE DETAIL';
export const DELETE_EXPENSE_DETAILS = '[EXPENSES-DETAIL APP] DELETE EXPENSE DETAIL';
export const GET_FILE_RECORDS_BY_TIMEFRAME = '[EXPENSES-DETAIL APP] GET FILE RECORDS TO BE BULK SAVED TO DETAILS';
export const GET_FILE_RECORDS_BY_TIMEFRAME_SUCCESS = '[EXPENSES-DETAIL APP] GET FILE RECORDS SUCCESS ';
export const GET_FILE_RECORDS_BY_TIMEFRAME_FAILURE = '[EXPENSES-DETAIL APP] GET FILE RECORDS FAILURE ';

export const OPEN_CREATE_EXPENSE_DETAILS_DIALOG = '[EXPENSES-DETAIL APP] OPEN CREATE EXPENSE DETAIL DIALOG';
export const OPEN_BULK_EXPENSE_DETAILS_DIALOG = '[EXPENSES-DETAIL APP] OPEN BULK EXPENSE DETAIL DIALOG';
export const CLOSE_CREATE_EXPENSE_DETAILS_DIALOG = '[EXPENSES-DETAIL APP] CLOSE CREATE EXPENSE DETAIL DIALOG';
export const CLOSE_BULK_EXPENSE_DETAILS_DIALOG = '[EXPENSES-DETAIL APP] CLOSE BULK EXPENSE DETAIL DIALOG';
export const OPEN_EDIT_EXPENSE_DETAILS_DIALOG = '[EXPENSES-DETAIL APP] OPEN EDIT EXPENSE DETAIL DIALOG';
