export const GET_CLIENT_INIT_REQUEST = '[CLIENT APP] GET CLIENT INIT REQUEST';
export const GET_CLIENT_SUCCESS = '[CLIENT APP] GET CLIENT SUCCESS';
export const GET_CLIENT_FAILURE = '[CLIENT APP] GET CLIENT FAILURE';
export const SAVE_CLIENT_INIT_REQUEST = '[CLIENT APP] SAVE CLIENT INIT REQUEST';
export const SAVE_CLIENT_SUCCESS = '[CLIENT APP] SAVE CLIENT SUCCESS';
export const SAVE_CLIENT_FAILURE = '[CLIENT APP] SAVE CLIENT FAILURE';
export const NEW_CLIENT = '[CLIENT APP] NEW CLIENT';
export const GET_DEPARTMENTS = '[CLIENT APP] GET DEPARTMENTS';
export const GET_COUNTRIES = '[CLIENT APP] GET COUNTRIES';
export const RELOAD_DATA = '[CLIENT APP] RELOAD DATA';

export const OPEN_CLIENT_GROUP_DETAIL_DIALOG = '[CLIENT APP] OPEN CLIENT GROUP DETAIL DIALOG';
export const EDIT_CLIENT_GROUP_DETAIL_DIALOG = '[CLIENT APP] EDIT CLIENT GROUP DETAIL DIALOG';
export const CLOSE_CLIENT_GROUP_DETAIL_DIALOG = '[CLIENT APP] CLOSE CLIENT GROUP DETAIL DIALOG';

export const CREATE_CLIENT_GROUP_DETAIL = '[CLIENT APP] CREATE CLIENT GROUP DETAIL';
export const DELETE_CLIENT_GROUP_DETAIL = '[CLIENT APP] DELETE CLIENT GROUP DETAIL';
