export const GET_CLIENTS_INIT_REQUEST = '[CLIENTS APP] GET CLIENTS INIT REQUEST';
export const GET_CLIENTS_SUCCESS = '[CLIENTS APP] GET CLIENTS SUCCESS';
export const GET_CLIENTS_FAILURE = '[CLIENTS APP] GET CLIENTS FAILURE';
export const SET_CLIENTS_SEARCH_TEXT = '[CLIENTS APP] SET CLIENTS SEARCH TEXT';
export const DELETE_CLIENT = '[CLIENTS APP] DELETE CLIENT';