export const GET_RECORD_FILE_INIT_REQUEST = '[FILE RECORD APP] GET RECORD FILE INIT_REQUEST';
export const GET_RECORD_FILE_SUCCESS = '[FILE RECORD APP] GET RECORD FILE SUCCESS';
export const GET_RECORD_FILE_FAILURE = '[FILE RECORD APP] GET RECORD FILE FAILURE';

export const SAVE_RECORD_FILE_INIT_REQUEST = '[FILE RECORD APP] SAVE RECORD FILE INIT_REQUEST';
export const SAVE_RECORD_FILE_SUCCESS = '[FILE RECORD APP] SAVE RECORD FILE SUCCESS';
export const SAVE_RECORD_FILE_FAILURE = '[FILE RECORD APP] SAVE RECORD FILE FAILURE';

export const NEW_RECORD_FILE = '[FILE RECORD APP] NEW RECORD FILE';
export const GET_TYPE_RECORD = '[FILE RECORD APP] GET TYPE RECORD';
export const GET_SUB_TYPE_RECORD = '[FILE RECORD APP] GET SUB TYPE RECORD';
