export const GET_RECORDS_INIT_REQUEST = '[FILE-RECORDS APP] GET RECORDS INIT REQUEST';
export const GET_RECORDS_SUCCESS = '[FILE-RECORDS APP] GET RECORDS SUCCESS';
export const GET_RECORDS_FAILURE = '[FILE-RECORDS APP] GET RECORDS FAILURE';

export const SET_RECORDS_SEARCH_TEXT = '[FILE-RECORDS APP] SET RECORDS SEARCH TEXT';
export const OPEN_CHANGE_STATE_DIALOG = '[FILE-RECORDS APP] OPEN CHANGE STATE DIALOG';
export const CLOSE_CHANGE_STATE_DIALOG = '[FILE-RECORDS APP] CLOSE CHANGE STATE DIALOG';

export const CHANGE_RECORD_STATUS_INIT = '[FILE-RECORDS APP] CHANGE RECORD STATUS INIT';
export const CHANGE_RECORD_STATUS_SUCCESS = '[FILE-RECORDS APP] CHANGE RECORD STATUS SUCCESS';
export const CHANGE_RECORD_STATUS_FAILURE = '[FILE-RECORDS APP] CHANGE RECORD STATUS FAILURE';

export const GET_STATUS_FLOW = '[FILE-RECORDS APP] GET STATUS FLOW';

export const OPEN_MERGE_RECORD_FILES_DIALOG = '[FILE-RECORDS APP] OPEN MERGE RECORD FILE DIALOG';
export const CLOSE_MERGE_RECORD_FILES_DIALOG = '[FILE-RECORDS APP] CLOSE MERGE RECORD FILE DIALOG';
export const MERGE_RECORD_FILE_INIT = '[FILE-RECORDS APP] MERGE RECORD FILE INIT';
export const MERGE_RECORD_FILE_SUCCESS = '[FILE-RECORDS APP] MERGE RECORD FILE SUCCESS';
export const MERGE_RECORD_FILE_FAILURE = '[FILE-RECORDS APP] MERGE RECORD FILE FAILURE';
