export const GET_STAMP_INV_OPTION_INIT_REQUEST = '[STAMP OPT APP] GET STAMP INV OPTION INIT REQUEST';
export const GET_STAMP_INV_OPTION_SUCCESS = '[STAMP OPT APP] GET STAMP INV OPTION SUCCESS';
export const GET_STAMP_INV_OPTION_FAILURE = '[STAMP OPT APP] GET STAMP INV OPTION FAILURE';
export const OPEN_STAMP_REPORT_DIALOG = '[STAMP OPT APP] OPEN STAMP REPORT DIALOG';
export const OPEN_EDIT_STAMP_OPTIONS_DIALOG = '[STAMP OPT APP] OPEN EDIT STAMP OPTIONS DIALOG';
export const OPEN_STAMP_OPTIONS_DIALOG = '[STAMP OPT APP] OPEN STAMP OPTIONS DIALOG';
export const CLOSE_STAMP_OPTIONS_DIALOG = '[STAMP OPT APP] CLOSE STAMP OPTIONS DIALOG';
export const SAVE_STAMP_INV_OPT_INIT_REQUEST = '[STAMP OPT APP] SAVE STAMP INV INIT REQUEST';
export const SAVE_STAMP_INV_OPT_SUCCESS = '[STAMP OPT APP] SAVE STAMP INV SUCCESS';
export const SAVE_STAMP_INV_OPT_FAILURE = '[STAMP OPT APP] SAVE STAMP INV FAILURE';
export const CLOSE_STAMP_REPORT_DIALOG = '[STAMP OPT APP] CLOSE STAMP REPORT DIALOG';

export const OPEN_CHANGE_STATE_OPT_DIALOG = '[STAMP OPT APP] OPEN CHANGE STATE DIALOG';
export const CLOSE_CHANGE_STATE_OPT_DIALOG = '[STAMP OPT APP] CLOSE CHANGE STATE DIALOG';
export const CHANGE_STAMP_INV_STATUS_INIT = '[STAMP OPT APP] CHANGE STAMP INV STATUS INIT';
export const CHANGE_STAMP_INV_STATUS_SUCCESS = '[STAMP OPT APP] CHANGE STAMP INV STATUS SUCCESS';
export const CHANGE_STAMP_INV_STATUS_FAILURE = '[STAMP OPT APP] CHANGE STAMP INV STATUS FAILURE';
export const GET_STATUS_FLOW = '[STAMP OPT APP] GET STATUS FLOW';

export const OPEN_MOVE_TO_RECORD_FILES_DIALOG = '[STAMP OPT APP] OPEN MOVE TO RECORD FILE DIALOG';
export const CLOSE_MOVE_TO_RECORD_FILES_DIALOG = '[STAMP OPT APP] CLOSE MOVE TO RECORD FILE DIALOG';
export const MOVE_TO_RECORD_FILE_INIT = '[STAMP OPT APP] MOVE TO RECORD FILE INIT';
export const MOVE_TO_RECORD_FILE_SUCCESS = '[STAMP OPT APP] MOVE TO RECORD FILE SUCCESS';
export const MOVE_TO_RECORD_FILE_FAILURE = '[STAMP OPT APP] MOVE TO RECORD FILE FAILURE';
