export const GET_NOMENCLATURES_INIT_REQUEST = '[NOMENCLATURE APP] GET NOMENCLATURES INIT REQUEST';
export const GET_NOMENCLATURES_SUCCESS = '[NOMENCLATURE APP] GET NOMENCLATURES SUCCESS';
export const GET_NOMENCLATURES_FAILURE = '[NOMENCLATURE APP] GET NOMENCLATURES FAILURE';

export const GET_NOMENCLATURE_INIT_REQUEST = '[NOMENCLATURE APP] GET NOMENCLATURE INIT REQUEST';
export const GET_NOMENCLATURE_SUCCESS = '[NOMENCLATURE APP] GET NOMENCLATURE SUCCESS';
export const GET_NOMENCLATURE_FAILURE = '[NOMENCLATURE APP] GET NOMENCLATURE FAILURE';

export const SAVE_NOMENCLATURE_INIT_REQUEST = '[NOMENCLATURE APP] SAVE NOMENCLATURE INIT REQUEST';
export const SAVE_NOMENCLATURE_SUCCESS = '[NOMENCLATURE APP] SAVE NOMENCLATURE SUCCESS';
export const SAVE_NOMENCLATURE_FAILURE = '[NOMENCLATURE APP] SAVE NOMENCLATURE FAILURE';
