export const GET_RECEIPT_INIT_REQUEST = '[RECEIPT APP] GET RECEIPT INIT_REQUEST';
export const GET_RECEIPT_SUCCESS = '[RECEIPT APP] GET RECEIPT SUCCESS';
export const GET_RECEIPT_FAILURE = '[RECEIPT APP] GET RECEIPT FAILURE';

export const SAVE_RECEIPT_INIT_REQUEST = '[RECEIPT APP] SAVE RECEIPT INIT_REQUEST';
export const SAVE_RECEIPT_SUCCESS = '[RECEIPT APP] SAVE RECEIPT SUCCESS';
export const SAVE_RECEIPT_FAILURE = '[RECEIPT APP] SAVE RECEIPT FAILURE';

export const NEW_RECEIPT = '[RECEIPT APP] NEW RECEIPT';

export const OPEN_CREATE_RECEIPT_DIALOG = '[RECEIPT APP] OPEN CREATE RECEIPT DIALOG';
export const CLOSE_CREATE_RECEIPT_DIALOG = '[RECEIPT APP] CLOSE RECEIPT DIALOG';
export const OPEN_EDIT_RECEIPT_DIALOG = '[RECEIPT APP] OPEN EDIT RECEIPT DIALOG';
export const DELETE_RECEIPT = '[RECEIPT APP] DELETE RECEIPT';
export const CREATE_RECEIPT = '[RECEIPT APP] CREATE RECEIPT';
