export const RECEIPT_REPORT_INIT_REQUEST = '[RECEIPT APP] RECEIPT REPORT INIT REQUEST';
export const RECEIPT_REPORT_SUCCESS = '[RECEIPT APP] RECEIPT REPORT SUCCESS';
export const RECEIPT_REPORT_FAILURE = '[RECEIPT APP] RECEIPT REPORT FAILURE';
