export const GET_RECEIPT_INIT_REQUEST = '[RECEIPT APP] GET RECEIPT INIT REQUEST';
export const GET_RECEIPT_SUCCESS = '[RECEIPT APP] GET RECEIPT SUCCESS';
export const GET_RECEIPT_FAILURE = '[RECEIPT APP] GET RECEIPT FAILURE';

export const SET_RECEIPT_SEARCH_TEXT = '[RECEIPT APP] SET RECEIPT SEARCH TEXT';

export const OPEN_CHANGE_STATE_RECEIPT_DIALOG = '[RECEIPT APP] OPEN CHANGE STATE RECEIPT DIALOG';
export const CLOSE_CHANGE_STATE_RECEIPT_DIALOG = '[RECEIPT APP] CLOSE CHANGE STATE RECEIPT DIALOG';

export const CHANGE_RECEIPT_STATUS_INIT = '[RECEIPT APP] CHANGE RECEIPT STATUS INIT';
export const CHANGE_RECEIPT_STATUS_SUCCESS = '[RECEIPT APP] CHANGE RECEIPT STATUS SUCCESS';
export const CHANGE_RECEIPT_STATUS_FAILURE = '[RECEIPT APP] CHANGE RECEIPT STATUS FAILURE';

export const GET_RECEIPT_STATUS_FLOW = '[RECEIPT APP] GET STATUS FLOW';

export const OPEN_PREVIEW_DOC_RECEIPT_DIALOG = '[RECEIPT APP] OPEN PREVIEW DOC RECEIPT DIALOG';
export const CLOSE_PREVIEW_DOC_RECEIPT_DIALOG = '[RECEIPT APP] CLOSE PREVIEW DOC RECEIPT DIALOG';
export const PREVIEW_DOC_INIT_REQUEST = '[RECEIPT APP] PREVIEW DOC INIT REQUEST';
export const PREVIEW_DOC_FAILURE = '[RECEIPT APP] PREVIEW DOC FAILURE';
