export const OPEN_INVOICE_SERIES_RECEIPT_DIALOG = '[RECEIPT APP] OPEN INVOICE SERIES RECEIPT DIALOG';
export const CLOSE_INVOICE_SERIES_RECEIPT_DIALOG = '[RECEIPT APP] CLOSE INVOICE SERIES RECEIPT DIALOG';
export const INVOICE_SERIES_INIT_REQUEST = '[RECEIPT APP] INVOICE SERIES INIT REQUEST';
export const INVOICE_SERIES_FAILURE = '[RECEIPT APP] INVOICE SERIES FAILURE';

export const OPEN_PREVIEW_RECEIPT_DIALOG_SUCCESS = '[RECEIPT APP] OPEN PREVIEW RECEIPT DIALOG';
export const OPEN_PREVIEW_RECEIPT_DIALOG_INIT = '[RECEIPT APP] OPEN PREVIEW RECEIPT DIALOG INIT';
export const OPEN_PREVIEW_RECEIPT_DIALOG_FAILURE = '[RECEIPT APP] OPEN PREVIEW RECEIPT DIALOG FAILURE';
export const CLOSE_PREVIEW_RECEIPT_DIALOG = '[RECEIPT APP] CLOSE PREVIEW RECEIPT DIALOG';
